[package]
name = "wvr-com"
version = "0.1.9"
authors = ["gurke.club <contact@gurke.club>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
message-io = "0.13"
bincode = "1.3"
serde = "1.0"
serde_derive = "1.0"
wvr-data = {git = "https://github.com/gurkeclub/wvr-data.git", branch="main"}
