[package]
name = "wvr-com"
version = "0.1.3"
authors = ["gurke.club <contact@gurke.club>"]
edition = "2018"

[dependencies]
message-io = "0.4"
serde = "1.0"
serde_derive = "1.0"
wvr-data = {git = "https://github.com/gurkeclub/wvr-data.git", branch="main"}
